# @author: Maryniak, Marius - Fachbereich Elektrotechnik, Westfälische Hochschule Gelsenkirchen

data:
  rgb:
    wms_url: https://www.wms.nrw.de/geobasis/wms_nw_dop
    wms_layer: nw_dop_rgb
  nir:
    wms_url: https://www.wms.nrw.de/geobasis/wms_nw_dop
    wms_layer: nw_dop_nir
  ndsm:
    wms_url: https://www.wms.nrw.de/geobasis/wms_nw_ndom
    wms_layer: nw_ndom
  epsg_code: 25832
  bounding_box:
    - 363210
    - 5715455
    - 364210
    - 5716455

preprocessing:
  color_codes_ndsm:
    - (0, 0, 0) - 0         # 0.0m  - 1.0m
    - (255, 255, 255) - 28  # 1.0m  - 1.5m
    - (31, 120, 180) - 57   # 1.5m  - 3.0m
    - (54, 214, 209) - 85   # 3.0m  - 5.0m
    - (64, 207, 39) - 113   # 5.0m  - 10.0m
    - (255, 255, 71) - 142  # 10.0m - 15.0m
    - (255, 206, 71) - 170  # 15.0m - 20.0m
    - (255, 127, 0) - 198   # 20.0m - 25.0m
    - (215, 25, 28) - 227   # 25.0m - 50.0m
    - (114, 0, 11) - 255    # > 50.0m

postprocessing:
  sieve_size: 2
  simplify: true

aggregation:
  tile_size:
    - 50
    - 100
  shp_path:

export_settings:
  output_dir_path: /Users/mrsmrynk/PycharmProjects/adois_app/output_dir
  shp_prefix: example
  export_raw_shp: true