# @author: Maryniak, Marius - Fachbereich Elektrotechnik, Westfälische Hochschule Gelsenkirchen

data:
  rgb:
    wms_url: https://www.wms.nrw.de/geobasis/wms_nw_dop
    wms_layer: nw_dop_rgb
  nir:
    wms_url: https://www.wms.nrw.de/geobasis/wms_nw_dop
    wms_layer: nw_dop_nir
  epsg_code: 25832
  boundary_shape_file_path:
  bounding_box:
    - 363210
    - 5715455
    - 364210
    - 5716455

postprocessing:
  sieve_size: 2
  simplify: true

aggregation:
  tile_size:
    - 50
    - 100
  shape_file_path:

export_settings:
  output_dir_path: /Users/mrsmrynk/PycharmProjects/adois/output_dir
  prefix: example
  export_raw_shape_file: true